config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
      sessions: 'users/sessions'
      }
  resources :zombies do
      resources :brains
  end
    
get "users/list", to: "zombies#user", as: "list_user"
    root to: 'zombies#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brain.rb
class Brain < ApplicationRecord
    belongs_to :zombie

    validates :flavor,presence:true
    validates :iq, numericality:{ only_integer:true, message:"Sólo números enteros"}
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end
  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
    @zombies = Zombie.all
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
    # @brain = Brain.new(brain_params)
      @zombie = Zombie.find(params[:zombie_id]);
      @brain = @zombie.brains.create(brain_params);

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'El Cerebro fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @brain }
          format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'El Cerebro fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'El Cerebro fue destruido exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:zombie_id, :flavor, :iq, :fresh)
    end
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/views/brains/_brain.html.erb
<table class="hover">
<%= div_for brain do%>
 
   <tbody>
<tr>
  <td>
  <td width ="1000">    
    <%= time_ago_in_words(brain.created_at)%>
    </td>
    <td width="500">   
    <%= brain.flavor%>
    </td>
    
    <td width="300">
    <%= brain.iq%>
    </td>
    <td width="500" >
    <% if brain.fresh%>
        <%= image_tag 'brains/imagen1.jpg',class:'brains_fresh'%>
        <%else%>
        <%= image_tag 'brains/imagen2.jpg',class:'brains_fresh'%>
        <%end%>
    </td>
      </td>
     </tr>
     </tbody>
      <% end %> 
         </table>

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <% options = options_from_collection_for_select(Zombie.all, 'id', 'name')%>
    <%= select_tag("brain[zombie_id]", options)%>    
  </div>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>
  
  <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div>
  
  <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/create.js.erb
var new_brain =$("<%= escape_javascript(render(:partial => @brain))%>").hide();
$('#brains').prepend(new_brain);
$('#brain_<%= @brain.id %>').fadeIn('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>Iq</th>
      <th>Fresh</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
        <td>
          <% if brain.fresh %>
            <%= image_tag'brains/fresh.png',class:'brains_fresh'%>
          <% else %>
             <%= image_tag 'brains/no_fresh.png',class:'brains_fresh'%>
          <%end %>
        </td>
        
        <td><%= link_to 'Show', brain, class:'button primary' %></td>
        <td><%= link_to 'Edit', edit_brain_path(brain), class:'button success' %></td>
        <td><%= link_to 'Destroy', brain, method: :delete, data: { confirm: 'Are you sure?', class:'button alert' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brain', new_brain_path %>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
</p>

<p>
  <strong>Iq:</strong>
  <%= @brain.iq %>
</p>

<p>
  <strong>Fresh:</strong>
  <%= @brain.fresh %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain), class:'button success'%> 
<%= link_to 'Back', brains_path, class:'button secondary'%>