config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: {
      sessions: 'users/sessions'
      }
  resources :zombies do
      resources :brains
  end
    
get "users/list", to: "zombies#user", as: "list_user"
    root to: 'zombies#index'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Zombies" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
 <h1>Z O M B I E S</h1>
     <% if user_signed_in? %>     
  <div class="top-bar">
      <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
              <li class="menu-text">
                  <a href="#">Menu</a>
                  <ul class="menu">
                      <%role= current_user.role%>
                      <% if role == "Subscriber"%>
                      <li><%= link_to "Mostrar Zombies", zombies_path %></li>
                      <% else%>
                      <li><%= link_to "Mostrar Zombies", zombies_path %></li>
                      <li><%= link_to "Agregar Nuevo Zombie", new_zombie_path %></li>
                      <%end%>
                      
                  </ul>
              </li>
          </ul>
      </div>
     <% else %>
      <div></div>
      <%end%>
    <% if admin_signed_in? %> 
    <%else%>  
    <div class="top-bar-right">
        <ul class="menu">
      <% if user_signed_in? %>
        <li>Bienvenido(a) <%= current_user.email%></li>
        <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
        <li><%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete%></li>
        <% else %>
        <li> Usuario</li>  
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Registro", new_user_registration_path %></li>
        <%end%>
            <%end%>
        </ul>    
      </div>  
  
      <% if user_signed_in? %>
      <%else%>
      <div class="top-bar-left">
        <ul class="menu">
      <% if admin_signed_in? %>
        <br>    
        <li><%= link_to "Editar perfil", edit_admin_registration_path %></li>
        <li><%= link_to "Cerrar sesion", destroy_admin_session_path, method: :delete%></li>
        <% else %>
         <li> Admin</li>  
        <li><%= link_to "Login", new_admin_session_path %></li>
        <li><%= link_to "Registro", new_admin_registration_path %></li>
        <%end%>
         <%end%>
        </ul>    
      </div>  
  </div>
      
 <%if notice %>
      
      <%end%>
<% if alert %>
      <p class="alert alert-danger"><%=alert%></p>
      <% end %>
    <%= yield %>

  </body>
</html>